<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-12-03T10:24:10 SAST" name="Default suite" finished-at="2022-12-03T10:24:21 SAST" duration-ms="10557">
    <groups>
    </groups>
    <test started-at="2022-12-03T10:24:10 SAST" name="Default test" finished-at="2022-12-03T10:24:21 SAST" duration-ms="10557">
      <class name="ui.VerifyTitleAndTextTest">
        <test-method signature="titleTest()[pri:0, instance:ui.VerifyTitleAndTextTest@35ef1869]" started-at="2022-12-03T10:24:10 SAST" name="titleTest" finished-at="2022-12-03T10:24:21 SAST" duration-ms="10469" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Title verification failed expected [Electronics, rrrtCars, Fashion, Collectibles & More | eBay] but found [Electronics, Cars, Fashion, Collectibles & More | eBay]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Title verification failed expected [Electronics, rrrtCars, Fashion, Collectibles & More | eBay] but found [Electronics, Cars, Fashion, Collectibles & More | eBay]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at ui.VerifyTitleAndTextTest.titleTest(VerifyTitleAndTextTest.java:39)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- titleTest -->
      </class> <!-- ui.VerifyTitleAndTextTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
